### PR TITLE
Repair Makefile to generate .html from .Rmd sources

### PR DESCRIPTION
**Pull request by fritzo**

### CODE REVIEW

**Comment by perrydv** [comment]
Thanks @fritzo. This looks like cleaned up use of make.  Can you add back in:

* `library(nimble);` (because otherwise in each html we'll get the output just from loading nimble, and it's cleaner without that).
* `library(methods);` (because for some reason this core R package for R classes needs to be explicitly loaded when using Rscript, or at least that has been the case in the past.

**Comment by fritzo** [comment]
Done. Thanks for reviewing, @perrydv !

**Comment by fritzo** [comment]
@perrydv What is the protocol for merging? In the past, my teams have required a reviewer to comment "LGTM" or ":+1:" in the comment thread before merging.

**Comment by perrydv** [comment]
LGTM

**Comment by perrydv** [comment]
Thanks @fritzo.  We make an effort to have someone else review and merge the PR, but I also like your suggestion.  In this case your fixes slipped past me so the reminder was good!  For small changes in areas where you are the only one involved, we sometimes just push them without the PR mechanism.

**Pull request merged**
