### PR TITLE
getNodeValueExpr

### PR DESCRIPTION
**Pull request by DRJP**
getNodeValueExpr, getNodeType, getNodeDistribution, getNodeParamExpr, isBinary, isDiscrete and isTruncated now introduced into the manual via some simple examples with the pump model in 2 new subsetions of section 6.

### CODE REVIEW

**Comment by paciorek** [comment]
I'm planning to do some work to cleanup our API calls for getting distribution and node information, including adding new functions as needed to round out the user experience. 

However, since that won't happen until after v0.6 release it probably makes sense to add this info in this PR into the manual.  I'm presuming this is just documentation for existing API calls already in Nimble.

Thoughts from anyone welcome.

**Comment by danielturek** [comment]
Pretty much all of these functions, I introduced into BUGS model classes for use in the conjugacy processing.  Quickly searching our code base, I see that's the only place most of them are used, although as @DRJP noticed they are generally handy functions for development of nimble functions.

So the main reason these never ended up in the User Manual is because I was adding them while developing the conjugacy system, really without attention to how they could be more widely useful.

One competing thought, however, is whether documentation for these is better placed in the [NIMBLE Developer Manual](https://github.com/nimble-dev/nimble-docs/tree/master/DeveloperManual), instead?

**Comment by paciorek** [comment]
Good question about the developer manual (which at this point in actuality
means putting it in the Wiki...).  However, if they are functions that
would be used in nimbleFunctions, then I think there's a good argument for
having them in the user manual.

**Comment by danielturek** [comment]
That raises the question, is the intent of the Developer Manual for those developing new NIMBLE algorithms?  Or those helping develop and expand the NIMBLE package itself?

And, since we've never really put any time into the Developer Manual, is it actually defunct, and already been replaced by the wiki?  (which is fine by me; but that's a decision we should collectively and openly make).

**Comment by paciorek** [comment]
Ok, after some thought and discussion with the core team, the plan is to revisit this for version 0.6-1 after I've had a chance to do a more thorough look at our API for distribution and node info. At that point I'll bring in the changes in this PR, likely into the nimbleFunction programming section of the manual or possibly into the Wiki.

**Comment by paciorek** [comment]
We subsequently greatly modified the manual and added help information for some of these individual functions/methods, so I'm closing this without merging.

**Pull request closed without merging**
